{include file='header_other.tpl'}
<section style="margin-top:600px;">
    <h2>Terms of use</h2>
    <p>Please read carefully the different terms of use of this site before browsing its pages. By connecting to this site, you accept, without reservation, the present terms and conditions. Also, in accordance with article n°6 of the Law n°2004-575 of June 21, 2004 for the confidence in the digital economy, the persons in charge of the present website are :</p>
    <h2>Website editors</h2>
    <ul>
        <li>BRIAND Lucile : lucile.briand@viacesi.fr</li>
        <li>ESSAHLAOUI Nissrine : nissrine.essahlaoui@viacesi.fr</li>
        <li>MILLON Louka : louka.millon@viacesi.fr</li>
    </ul>
    <h2>Conditions of use</h2>
    <p>This site is proposed in different web languages (HTML5, CSS3, Javascript, etc...) for a better comfort of use and a more pleasant graphics. We recommend that you use modern browsers such as Internet Explorer, Safari, Firefox, Google Chrome, etc... The creators use all means at their disposal to ensure reliable information and a reliable update of their website. However, errors or omissions may occur. The user must therefore ensure the accuracy of information from the team, and report any changes to the site that he considers useful. The team is in no way responsible for the use made of this information, and for any direct or indirect prejudice that may result from it.</p>
    <h3>Cookies :</h3>
    <p>The website may ask you to accept cookies for statistical and display purposes. A cookie is a piece of information placed on your hard drive by the server of the site you are visiting. It contains several pieces of data that are stored on your computer in a simple text file that a server accesses to read and record information. Some parts of this site cannot be functional without the acceptance of cookies.</p>
    <h3>Contractual data limitations :</h3>
    <p>The information contained on this site is as accurate as possible and the site is updated at different times of the year, but may contain inaccuracies or omissions. If you notice a gap, error or what seems to be a malfunction, please report it by email, to the address of one of the team members, describing the problem as precisely as possible (page with problem, type of computer and browser used, ...). Any downloaded content is done at the user's own risk and under his sole responsibility. As a result, we cannot be held responsible for any damage to the user's computer or for any loss of data resulting from the download. Moreover, the user of the site undertakes to access the site using recent equipment, free of viruses and with a last generation updated browser.</p>
    <h3>Intellectual Property :</h3>
    <p>All the content of this site, including, but not limited to, graphics, images, texts, videos, animations, sounds, logos, gifs and icons, as well as their formatting, are the exclusive property of the team, with the exception of trademarks, logos or content belonging to other partner companies or authors. Any reproduction, distribution, modification, adaptation, retransmission or publication, even partial, of these different elements is strictly forbidden without the express written consent of the team. This representation or reproduction, by any means whatsoever, constitutes an infringement punishable by articles L.335-2 and following of the Code of Intellectual Property. The non-respect of this prohibition constitutes an infringement that can engage the civil and penal liability of the infringer. In addition, the owners of the copied Contents could bring a legal action against you.</p>
</section>